### ISSUE TITLE
Cron's Roadmap (v0)

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/cron#1]
This issue contains the roadmap and/or feature lookahead for Cron v0.

- [x] `cron(value)`: Initializer function that sets a variable to reactive state.
- [x] `cron().get()`: Returns the value of the reactive state.
- [x] `cron().set()`: Updates the value of reactive state and calls any listeners.
- [x] `cron().mut(method, args)`: Calls the given method on the state with arguments.
- [x] `cron().mat(property)`: Returns the given property of the state.
- [x] `cron().listen()`: Runs callback whenever reactive state is updated.
- [x] `cron().batch()`: Runs updates and only calls listeners at end.
- [x] `cron.deafen()`: Stops all listeners from activating, or a specific listener.
